{{ if  .Values.backupconfig.enabled  }}
apiVersion: v1
kind: Secret
metadata:
    name: gc-backup-secret
type: Opaque
stringdata:
    config.yaml: |
      crypt4ghPublicKey: "/.secrets/keys/key.pub.pem"
      crypt4ghPrivateKey: "/.secrets/keys/key.sec.pem"
      crypt4ghPassphrase: {{ .Values.backupkeys.keypassphrase }}
      loglevel: {{ .Values.backupconfig.loglevel }}
      db:
        host: {{ .Values.backupconfig.db.host }}
        user: {{ .Values.backupconfig.db.user }}
        password: {{ .Values.backupconfig.db.password }}
        database: {{ .Values.backupconfig.db.database }}
        sslmode: {{ .Values.backupconfig.db.sslmode }}
      s3:
        url: {{ .Values.backupconfig.s3.url }}
        accesskey: {{ .Values.backupconfig.s3.accesskey }}
        secretkey: {{ .Values.backupconfig.s3.secretkey }}
        bucket: {{ .Values.backupconfig.s3.bucket }}
    key.pub.pem: {{ .Values.backupkeys.publickey | quote }}
    key.sec.pem: {{ .Values.backupkeys.privatekey | quote }}
{{ end }}