apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  accesskey: {{ .Values.minio.accesskey }}
  secretkey: {{ .Values.minio.secretkey }}
  components-access: {{ .Values.minio.componentskey }}
  components-secret: {{ .Values.minio.componentssecret }}
  url: "{{ .Values.minio.url }}"
{{ if .Values.minio.internal_url }}
  internal_url: "{{ .Values.minio.internal_url }}"
{{ end }}