apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flower
spec:
  podSelector:
    matchLabels:
      service: flower
  policyTypes:
    - Egress
    - Ingress
  ingress:
  egress:
    - to:
        - podSelector:
            matchLabels:
              service: redis
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - namespaceSelector:
            matchLabels:
               kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP