
domainName: storprovning.test

certificates:
  invalidWorkaround: true
  issuer: selfsign-issuer
  clusterIssuer: null
  handle: true

images:
  web: public.ecr.aws/diag-nijmegen/grand-challenge/web@sha256:7d37247e2ee25ab13a773e0b08ad0d7e175bd05c58c9703b9e1befe17db7d953
  http: public.ecr.aws/diag-nijmegen/grand-challenge/http@sha256:9b3183cb3047c67f8e5e6d6734ddef992f02a112368f5eed61b1238b2de0fbeb
  minio: minio/minio@sha256:02b9d0234025a31b1fb2a52697b62a18a4fbd0db03cbd83dfc09fc48773b718c
  postgres: postgres@sha256:20ca3cae0626ba55c512d687adf72e3055e1233b074d9f80d379dcc012cc63b6

postgres:
  username: username
  password: password
  database: database

minio:
  accesskey: accesskey
  secretkey: secretkey