apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: registry
spec:
  podSelector:
    matchLabels:
      service: registry
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              service: celery-beat
              service: web
              service: celery-worker
              algorithm: job
      ports:
        - protocol: TCP
          port: 5000
  egress:
