apiVersion: v1
kind: Secret
metadata:
  name: registry-pullsecret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: >
      {"auths":{
        "{{ .Values.registry.url }}":{
          "username": "{{ .Values.registry.username }}",
          "password": "{{ .Values.registry.password }}",
          "email": "{{ .Values.registry.email }}",
          "auth": "{{ printf "%s:%s" .Values.registry.username 
                                     .Values.registry.password |
                      b64enc }}"
                                     } 
               }
      }
