apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
type: Opaque
stringData:
  username: {{ .Values.registry.username }}
  password: {{ .Values.registry.password }}
  prefix: {{ .Values.registry.prefix }}
  url: "{{ .Values.registry.url }}"
