apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grand-challengeorg-workstations
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              service: workstation-proxy
  podSelector:
    matchLabels:
      service: workstation-proxy
  policyTypes:
  