apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: grand-challengeorg-default
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
  podSelector:
    matchLabels:
