apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
  labels:
    service: redis
  name: redis
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      annotations:
      labels:
        service: redis
    spec:
      containers:
        - args:
            - redis-server
            - --appendonly
            - "yes"
          image: redis:5.0
          name: redis
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: redis-data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            # NOTE: This is a pretty wild guess
            storage: 1Gi
