apiVersion: v1
kind: ServiceAccount
metadata:
  name: gc-launcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator
rules:
- apiGroups: ["batch"]
  resources: ["jobs", "jobs/status"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "jobs/log"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-jobs
subjects:
- kind: ServiceAccount
  name: gc-launcher
  apiGroup: ""
roleRef:
  kind: Role
  name: job-creator
  apiGroup: ""
