apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        service: web
    spec:
      containers:
        - args:
            - bash
            - -c
            - "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: accesskey
                  name: minio-secret
            - name: AWS_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secretkey
                  name: minio-secret
            - name: COMPONENTS_DEFAULT_BACKEND
              value: grandchallenge.components.backends.docker.DockerExecutor
            - name: COMPONENTS_REGISTRY_INSECURE
              value: "true"
            - name: DEBUG
              value: "true"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: database
                  name: postgres-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgres-secret
            - name: POSTGRES_PORT
              value: "5432"
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
          image: public.ecr.aws/diag-nijmegen/grand-challenge/web:latest
          name: web
          resources: {}
      restartPolicy: Always
