apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    kube-score/ignore: networkpolicy-targets-pod
  name: algorithm-job
spec:
  podSelector:
    matchLabels:
      algorithm: job 
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              service: celery-beat
              service: celery-worker
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              service: minio
      ports:
        - protocol: TCP
          port: 9000
    - to:
        - namespaceSelector:
            matchLabels:
               kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP