apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: celery-worker
spec:
  podSelector:
    matchLabels:
      service: celery-worker
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              service: http
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - podSelector:
            matchLabels:
              service: postgres
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              service: redis
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - podSelector:
            matchLabels:
              service: minio
      ports:
        - protocol: TCP
          port: 9000
    - to:
        - ipBlock:
            # Gah!
            cidr: 10.0.0.0/8
      ports:
        - protocol: TCP
          port: 443
