apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: celery-worker
spec:
  podSelector:
    matchLabels:
      service: celery-worker
  policyTypes:
    - Egress
    - Ingress
  ingress:
  egress:
    - to:
        - podSelector:
            matchLabels:
              service: registry
      ports:
        - protocol: TCP
          port: 5000
    - to:
        - podSelector:
            matchLabels:
              service: postgres
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              service: redis
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - podSelector:
            matchLabels:
              service: minio
      ports:
        - protocol: TCP
          port: 9000
    - to:
        - podSelector:
            matchLabels:
              algorithm: job
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - ipBlock:
            cidr: {{ .Values.publicIP }}
        - ipBlock:
            cidr: {{ .Values.internalAPIIP }}
        - ipBlock:
            cidr: {{ .Values.registry.ip }}
      ports:
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: {{ .Values.internalAPIEndpoints }}
      ports:
        - protocol: TCP
          port: {{ .Values.internalAPIPort }}

    - to:
        - namespaceSelector:
            matchLabels:
               kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
