apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    service: flower
  name: flower
spec:
  ports:
    - name: "5555"
      port: 5555
      targetPort: 5555
  selector:
    service: flower
status:
  loadBalancer: {}
