apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    service: minio
  name: minio
spec:
  clusterIP: None
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    service: minio
