apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    service: postgres
  name: postgres
spec:
  clusterIP: None
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    service: postgres
