apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis
spec:
  podSelector:
    matchLabels:
      service: redis
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              service: celery-beat
              service: web
              service: celery-worker
      ports:
        - protocol: TCP
          port: 6379
  egress:
