apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kube-score/ignore: container-image-pull-policy, pod-probes, container-security-context-user-group-id
  labels:
    service: redis
  name: redis
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      annotations:
      labels:
        service: redis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
      containers:
        - args:
            - redis-server
            - --appendonly
            - "yes"
          image: {{ .Values.images.redis }}
          name: redis
          securityContext: 
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /data
              name: redis-data
          resources:
            limits:
              cpu: "4"
              memory: 256Mi
              ephemeral-storage: 32Mi
            requests:
              cpu: "1"
              memory: 64Mi
              ephemeral-storage: 32Mi
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            # NOTE: This is a pretty wild guess
            storage: 1Gi
