apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    service: registry
  name: registry
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    service: registry
