apiVersion: v1
kind: ServiceAccount
metadata:
  name: gc-launcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator
rules:
- apiGroups: ["batch"]
  resources: ["jobs", "jobs/status"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "jobs/log"]
  verbs: ["get", "watch", "list", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-jobs
subjects:
- kind: ServiceAccount
  name: gc-launcher
roleRef:
  kind: Role
  name: job-creator
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: workstation-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: discovery-role
rules:
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses", "ingressclasses"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["services", "endpoints", "secrets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingress/status"]
  verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discover-objects
subjects:
- kind: ServiceAccount
  name: workstation-proxy
roleRef:
  kind: Role
  name: discovery-role
  apiGroup: rbac.authorization.k8s.io
