apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    service: workstation-proxy
  name: workstation-proxy
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "9101"
      port: 9101
      targetPort: 9101
  selector:
    service: workstation-proxy
status:
  loadBalancer: {}
